ktor:
    application:
        modules:
            - com.ApplicationKt.module
    deployment:
        port: 8080
database:
  url: "jdbc:postgresql://localhost:5432/ktor_db"
  user: "postgres"
  password: "password"
  driver: "org.postgresql.Driver"